# https://www.confluent.io/blog/kafka-listeners-explained/
# https://github.com/wurstmeister/kafka-docker
# https://github.com/edenhill/kafkacat#examples
# https://github.com/confluentinc/confluent-kafka-python/issues/452

version: '2'

networks:
  kafkatest:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - kafkatest
    ports:
     - "2181:2181"
  kafka:
    build: .
    ports:
     - "9092:9092"
    expose:
     - "9093"
    hostname: kafka
    networks:
      - kafkatest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock