---
- hosts: digitalocean
  remote_user: root
  become: true
  roles:
    - docker-ce
    - web
    - role: service
      var: 
        service_name: auth-service
        service_port: 8081
    - role: service
      var: 
        service_name: user-service
        service_port: 8083
