- name: Get infos on container
  docker_container_info:
    name: app
  register: result

- name: kill container and restart
  command: docker kill app
  when: result.exists

- name: remove container
  command: docker rm app
  when: result.exists

- name: remove image:
  command: docker image rm fuvkdocker888/shopping -f
  when: result.exists

- name: pull image
  command: docker pull fuvkdocker888/shopping

- name: restart app
  command: docker run -it -d -p 3000:3000 --name=app fuvkdocker888/shopping
