name: Master build or pull request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      # - name: docker build app
      #   run: "docker build -f app/Dockerfile -t fuvkdocker888/shopping-app:latest ."
      # - name: push app image to docker hub
      #   run: "docker push fuvkdocker888/shopping-app:latest"

      - name: docker build auth service
        run: "docker build -f auth-service/Dockerfile -t fuvkdocker888/auth-service:latest ."
      - name: push auth service image to docker hub
        run: "docker push fuvkdocker888/auth-service:latest"

      # - name: docker build user service
      #   run: "docker build -f user-service/Dockerfile -t fuvkdocker888/user-service:latest ."
      # - name: push user service image to docker hub
      #   run: "docker push fuvkdocker888/user-service:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/ansible
        env:
          VAULT_PASS: ${{secrets.VAULT_PASS}}